In [1]:
import numpy as np # numpy kütüphanesi np takma adı ile projeye dahil ediyoruz.

In [2]:
dizi=np.full((4,3),5)
dizi

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [4]:
# yeni bir numpy dizesi oluşturuyoruz.
np.array([1,2,3])

array([1, 2, 3])

In [10]:
# olusturdugumuz diziyi bir degiskene aktarıyoruz
dizi=np.array(["elma","erik","iğde"])
dizi

array(['elma', 'erik', 'iğde'], dtype='<U4')

In [11]:
dizi=np.array([1,2,3])

In [12]:
dizi=np.array([1,2,3.14])

In [17]:
# bir boyutlu dizi olusturma
birboyut=np.array([1,2,3,4])
# iki boyutlu dizi olusturma
ikiboyut=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [18]:
birboyut

array([1, 2, 3, 4])

In [19]:
ikiboyut

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
np.zeros(7) #7 sıfırdan olusan tek boyutlu dizi olusturur

array([0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros((2,3),dtype=int) #* sıfırdan olusan iki boyutlu int dizisi olusturur

array([[0, 0, 0],
       [0, 0, 0]])

In [22]:
np.ones(3)

array([1., 1., 1.])

In [23]:
np.full((4,3),5) #5 sayısından olusan 2*3 luk dizi

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [25]:
np.arange(2,22,5) # baslangıc bitis ve artıs degerine gore dizi olusturur

array([ 2,  7, 12, 17])

In [26]:
np.linspace(2,10,num=7) # baslangıc ve bitis degeri aralıgında belirtilen miktarda esit aralık 

array([ 2.        ,  3.33333333,  4.66666667,  6.        ,  7.33333333,
        8.66666667, 10.        ])

In [29]:
np.random.randint(0,10,5) # 0-10 aralıgında rastgele 5 sayıdan olusan bir boyutlu dizi 

array([1, 5, 6, 5, 0])

In [31]:
# dizilerin eleman sayısını ogrenmek icin shape komutu kullanılır 
dizi=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
dizi.shape

(3, 4)

In [32]:
# ndim dizi boyutunu ogrenmek icin kullanılır 
dizi.ndim

2

In [33]:
# size dizideki toplam eleman sayısını gosterir
dizi.size

12

In [36]:
# dizideki her bir elemanın bayt cinsinden degeri verir 
dizi.itemsize

4

In [37]:
np.random.randint(0,10,5) #0-10 aralıgında

array([3, 6, 3, 9, 1])