In [1]:
import numpy as np # adı değiştirmek için kullanılır.
np.array([1,2,3]) # dizi oluşturmak için kullanılır. 


array([1, 2, 3])

In [3]:
dizi=np.array([1,2,3,3.14])
dizi #  bir ondalık sayı, tam sayı olanları da ondalık sayı hâline çevirir.

array([1.  , 2.  , 3.  , 3.14])

In [4]:
dizi=np.array([1,2,3,3.14],dtype=int)
dizi # tüm elemanları tek tipe dönüştürmeyi uygular.

array([1, 2, 3, 3])

In [5]:
birboyut=np.array([1,2,3])
birboyut # bu kodları yazarak bir boyutlu dizi oluşturur. 

array([1, 2, 3])

In [6]:
ikiboyut = np.array([[1,2,3], [4,5,6]])
ikiboyut # iki boyutlu bir dizi oluşturur.

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.zeros(5) # zeros fonksiyonunu kullanarak sıfırlardan oluşan NumPy dizisi oluşturulur.

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros((4,3)) # sıfırdan numpy dizisi oluşturur.

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.zeros((4,3),dtype=int) # sıfırdan numpy dizisi oluşturur.

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])